version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-stable_ocaml-4.06.0
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Update apt packages list
          command: sudo apt-get update
      - run:
          name: Install required packages
          command: sudo apt install build-essential libgmp-dev libpcre3-dev pkg-config m4 libssl-dev libsqlite3-dev wget ca-certificates unzip aspcud libncurses-dev uuid-runtime zlib1g-dev -y
